-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 23-Nov-2023 às 16:39
-- Versão do servidor: 10.4.17-MariaDB
-- versão do PHP: 7.3.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `questao`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `questoes`
--

CREATE TABLE `questoes` (
  `id` int(11) NOT NULL,
  `Pergunta` longtext DEFAULT NULL,
  `Area` varchar(90) DEFAULT NULL,
  `Nome` varchar(45) NOT NULL,
  `Foto` varchar(90) DEFAULT NULL,
  `Questionario_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `questoes`
--

INSERT INTO `questoes` (`id`, `Pergunta`, `Area`, `Nome`, `Foto`, `Questionario_id`) VALUES
(0, '(Enem 2020). A Pesquisa Nacional por Amostra de Domicílios (Pnad) é uma pesquisa feita anualmente pelo IBGE, exceto nos anos em que há Censo. Em um ano, foram entrevistados 363 mil jovens para fazer um levantamento sobre suas atividades profissionais e/ou acadêmicas. Os resultados da pesquisa estão indicados no gráfico. ', '4', '', 'ftmat1.png', 1),
(1, '(ENEM - 2018) \r\n\r\n       A Transferência Eletrônica Disponível (TED) é uma transação financeira de valores entre diferentes bancos. Um economista decide analisar os valores enviados por meio de TEDs entre cinco bancos (1, 2, 3, 4 e 5) durante um mês. Para isso, ele dispõe esses  valores em uma matriz A = [aij], em que 1≤i≤5\r\n1≤�≤5\r\n e 1≤j≤5\r\n1≤�≤5\r\n, e o elemento aij corresponde ao total proveniente das operações feitas via TED, em milhão de real, transferidos do banco i para o banco j durante o mês. Observe que os elementos aij = 0, uma vez que TED é uma transferência entre bancos distintos. Esta é a matriz obtida para essa análise: ', '4', '', 'ftmat2.png', 1),
(2, '(ENEM - 2010) \r\n\r\nA classificação de um país no quadro de medalhas nos jogos olímpicos depende do número de medalhas de ouro que obteve na competição, tendo como critérios de desempate o número de medalhas de prata seguido do número de medalhas de bronze conquistados. Nas Olimpíadas de 2004, o Brasil foi o décimo sexto colocado no quadro de medalhas, tendo obtido 5 medalhas de \r\nouro, 2 de prata e 3 de bronze. Parte desse quadro de medalhas é reproduzida a seguir. ', '4', '', 'ftmat3.png', 1),
(3, '(ENEM - 2010) \r\n\r\nA classificação de um país no quadro de medalhas nos jogos olímpicos depende do número de medalhas de ouro que obteve na competição, tendo como critérios de desempate o número de medalhas de prata seguido do número de medalhas de bronze conquistados. Nas Olimpíadas de 2004, o Brasil foi o décimo sexto colocado no quadro de medalhas, tendo obtido 5 medalhas de \r\nouro, 2 de prata e 3 de bronze. Parte desse quadro de medalhas é reproduzida a seguir. ', '4', '', 'ftmat3.png', 1),
(5, '(ENEM - 2016) \r\n\r\nEm uma empresa de móveis, um cliente encomenda um guarda-roupa nas dimensões 220 cm de altura, 120 cm de largura e 50 cm de profundidade. Alguns dias depois, o projetista, com o desenho elaborado na escala 1 : 8, entra em contato com o cliente para fazer sua apresentação. No momento da impressão, o profissional percebe que o desenho não caberia na folha de papel que costumava usar. Para resolver o problema, configurou a impressora para que a figura fosse reduzida em 20%. \r\n\r\n  \r\n\r\nA altura, a largura e a profundidade do desenho impresso para a apresentação serão, respectivamente, ', '4', '', '', 1),
(6, '(Enem 2017)  \r\n\r\nRaios de luz solar estão atingindo a superfície de um lago formando um ângulo x com a sua superfície, conforme indica a figura. Em determinadas condições, pode-se supor que a intensidade luminosa desses raios, na superfície do lago, seja dada aproximadamente por l(x) = k . sen(x)  sendo k uma constante, e supondo-se que x está entre 0° e 90°. ', '4', '', 'ftmat6.png', 1),
(7, '(ENEM - 2013) Para oferecer acessibilidade aos portadores de dificuldades de locomoção, é utilizado, em ônibus e automóveis, o elevador hidráulico. Nesse dispositivo é usada uma bomba elétrica, para forçar um fluido a passar de uma tubulação estreita para outra mais larga, e dessa forma acionar um pistão que movimenta a plataforma. Considere um elevador hidráulico cuja área da cabeça do pistão seja cinco vezes maior do que a área da tubulação que sai da bomba. Desprezando o atrito e considerando uma aceleração gravitacional de 10m/s2,  deseja-se elevar uma pessoa de 65 kg em uma cadeira de rodas de 15 kg sobre a plataforma de 20 kg.  \r\n\r\nQual deve ser a força exercida pelo motor da bomba sobre o fluido, para que o cadeirante seja elevado com velocidade constante? ', '1', '', '', 1),
(8, '(ENEM - 2013) Para oferecer acessibilidade aos portadores de dificuldades de locomoção, é utilizado, em ônibus e automóveis, o elevador hidráulico. Nesse dispositivo é usada uma bomba elétrica, para forçar um fluido a passar de uma tubulação estreita para outra mais larga, e dessa forma acionar um pistão que movimenta a plataforma. Considere um elevador hidráulico cuja área da cabeça do pistão seja cinco vezes maior do que a área da tubulação que sai da bomba. Desprezando o atrito e considerando uma aceleração gravitacional de 10m/s2,  deseja-se elevar uma pessoa de 65 kg em uma cadeira de rodas de 15 kg sobre a plataforma de 20 kg.  \r\n\r\nQual deve ser a força exercida pelo motor da bomba sobre o fluido, para que o cadeirante seja elevado com velocidade constante? ', '1', '', 'fisica2.png', 1),
(9, '(ENEM - 2013) Em um piano, o Dó central e a próxima nota Dó (Dó maior) apresentam sons parecidos, mas não idênticos. É possível utilizar programas computacionais para \r\nexpressar o formato dessas ondas sonoras em cada uma das situações como apresentado nas figuras, em que estão indicados intervalos de tempo idênticos (T). \r\nA razão entre as frequências do Dó central e do Dó maior é de: \r\n\r\nA protanopia é um tipo de daltonismo em que há diminuição ou ausência de receptores da cor vermelha. Considere um teste com dois voluntários: uma pessoa com visão normal e outra com caso severo de protanopia. Nesse teste, eles devem escrever a cor dos cartões que lhes são mostrados. São utilizadas as cores indicadas na figura. \r\n\r\n  \r\n\r\nPara qual cartão os dois voluntários identificarão a mesma cor? ', '1', '', 'fisica3.png', 1),
(10, '(Enem 2016) Durante a primeira fase do projeto de uma usina de geração de energia elétrica, os engenheiros da equipe de avaliação de impactos ambientais procuram saber se esse projeto está de acordo com as normas ambientais. A nova planta estará localizada a beira de um rio, cuja temperatura média da água é de 25 ºC, e usará a sua água somente para refrigeração. O projeto pretende que a usina opere com 1,0 MW de potência elétrica e, em razão de restrições técnicas, o dobro dessa potência será dissipada por seu sistema de arrefecimento, na forma de calor. Para atender a resolução número 430, de 13 de maio de 2011, do Conselho Nacional do Meio Ambiente, com uma ampla margem de segurança, os engenheiros determinaram que a água só poderá ser devolvida ao rio com um aumento de temperatura de, no máximo, 3 ºC em relação à temperatura da água do rio captada pelo sistema de arrefecimento. Considere o calor específico da água igual a 4kJ/(kg ºC). \r\n\r\nPara atender essa determinação, o valor mínimo do fluxo de água, em kg/s, para a refrigeração da usina deve ser mais próximo de ', '1', '', '', 1),
(11, '(ENEM 2014) Ao sintonizarmos uma estação de rádio ou um canal de TV em um aparelho, estamos alterando algumas características elétricas de seu circuito receptor. Das inúmeras ondas eletromagnéticas que chegam simultaneamente ao receptor, somente aquelas que oscilam com determinada frequência resultarão em máxima absorção de energia. \r\n\r\nO fenômeno descrito é a: ', '1', '', '', 1),
(12, '(ENEM - 2014) \r\n\r\nA liberação dos gases clorofluorcarbonos (CFCs) na atmosfera pode provocar depleção de ozônio (O3) na estratosfera. O ozônio estratosférico é responsável por absorver parte da radiação ultravioleta emitida pelo Sol, a qual é nociva aos seres vivos. Esse processo, na camada de ozônio, é ilustrado simplificadamente na figura. \r\nQuimicamente, a destruição do ozônio na atmosfera por gases CFCs é decorrência da ', '1', '', 'quim1.png', 1),
(13, '(ENEM - 2017) \r\n\r\nUm fato corriqueiro ao se cozinhar arroz é o derramamento de parte da água de cozimento sobre a chama azul do fogo, mudando-a para uma chama amarela. Essa mudança de cor pode suscitar interpretações diversas, relacionadas às substâncias presentes na água de cozimento. Além do sal de cozinha (NaCl) nela se encontram carboidratos, proteínas e sais minerais. \r\n\r\nCientificamente, sabe-se que essa mudança de cor da chama ocorre pela ', '1', '', '', 1),
(14, '(ENEM - 2015) \r\n\r\nA soda cáustica pode ser usada no desentupimento de encanamentos domésticos e tem, em sua composição, o hidróxido de sódio como principal componente, além de algumas impurezas. A soda normalmente é comercializada na forma sólida, mas que apresenta aspecto “derretido” quando exposta ao ar por certo período. \r\n\r\n  \r\n\r\nO fenômeno de “derretimento” decorre da ', '1', '', '', 1),
(15, '(ENEM - 2020) \r\n\r\nUm microempresário do ramo de cosméticos utiliza óleos essenciais e quer produzir um creme com fragrância de rosas. O principal componente do óleo de rosas tem cadeia poli-insaturada e hidroxila em carbono terminal. O catálogo dos óleos essenciais apresenta, para escolha da essência, estas estruturas químicas: \r\n\r\nQual substância o empresário deverá utilizar?  ', '1', '', 'quim4.png', 1),
(16, '(ENEM 2014) O boxe está perdendo cada vez mais espaço para um fenômeno relativamente recente do esporte, o MMA. E o maior evento de Artes Marciais Mistas do planeta é o Ultimate Fighting Championship, ou simplesmente UFC. O ringue, com oito cantos, foi desenhado para deixar os lutadores com mais espaço para as lutas. Os atletas podem usar as mãos e aplicar golpes de jiu-jitsu. Muitos podem falar que a modalidade é uma espécie de vale-tudo, mas isso já ficou no passado: agora, a modalidade tem regras e acompanhamento médico obrigatório para que o esporte apague o estigma negativo. \r\n\r\nCORREIA, D. UFC: saiba como o MMA nocauteou o boxe em oito golpes. Veja, 10 jun. 2011 (fragmento) \r\n\r\nO processo de modificação das regras do MMA retrata a tendência de redimensionamento de algumas práticas corporais, visando enquadrá-las em um determinado formato. \r\nQual o sentido atribuído a essas transformações incorporadas historicamente ao MMA? ', '3', '', '', 1),
(17, '(ENEM 2016) \r\n\r\nTEXTO I \r\n\r\nNesta época do ano, em que comprar compulsivamente é a principal preocupação de boa parte da população, é imprescindível refletirmos sobre a importância da mídia na propagação de determinados comportamentos que induzem ao consumismo exacerbado. No clássico livro O capital, Karl Marx aponta que no capitalismo os bens materiais, ao serem fetichizados, passam a assumir qualidades que vão além da mera materialidade. As coisas são personificadas e as pessoas são coisificadas. Em outros termos, um automóvel de luxo, uma mansão em um bairro nobre ou a ostentação de objetos de determinadas marcas famosas são alguns dos fatores que conferem maior valorização e visibilidade social a um indivíduo. \r\n\r\nLADEIRA, F. F. Reflexões sobre o consumismo. Disponível em: http://observatoriodaimprensa.com.br. \r\nAcesso em 18 Jan.2015. \r\n\r\nTEXTO II \r\n\r\nTodos os dias, em algum nível, o consumo atinge nossa vida, modifica nossas relações, gera e rege sentimentos, engendra fantasias, aciona comportamentos, faz sofrer, faz gozar. Às vezes constrangendo-nos em nossas ações no mundo, humilhando e aprisionando, às vezes ampliando nossa imaginação e nossa capacidade de desejar, consumimos e somos consumidos. Numa época toda codificada como a nossa, o código da alma (o código do ser) virou código do consumidor! Fascínio pelo consumo, fascínio do consumo. Felicidade, luxo, bem-estar, boa forma, lazer, elevação espiritual, saúde, turismo, sexo, família e corpo são hoje reféns da engrenagem do consumo. \r\n\r\nBARCELLOS, G. A alma do consumo. Disponível em: www.diplomatique.org.br. \r\nAcesso em 18 jan 2015. \r\n\r\nEsses textos propõem uma reflexão crítica sobre o consumismo. Ambos partem do ponto de vista de que esse hábito ', '3', '', '', 1),
(18, '(ENEM 2016) O senso comum é que só os seres humanos são capazes de rir. Isso não é verdade? \r\n\r\nNão. O riso básico – o da brincadeira, da diversão, da expressão física do riso, do movimento da face e da vocalização — nós compartilhamos com diversos animais. Em ratos, já foram observadas vocalizações ultrassônicas – que nós não somos capazes de perceber – e que eles emitem quando estão brincando de “rolar no chão”. Acontecendo de o cientista provocar um dano em um local específico no cérebro, o rato deixa de fazer essa vocalização e a brincadeira vira briga séria. Sem o riso, o outro pensa que está sendo atacado. O que nos diferencia dos animais é que não temos apenas esse mecanismo básico. Temos um outro mais evoluído. Os animais têm o senso de brincadeira, como nós, mas não têm senso de humor. O córtex, a parte superficial do cérebro deles, não é tão evoluído como o nosso. Temos mecanismos corticais que nos permitem, por exemplo, interpretar uma piada. \r\n\r\nDisponível em http://globonews.globo.com. Acesso em 31 maio 2012 (adaptado) \r\n\r\nA coesão textual é responsável por estabelecer relações entre as partes do texto. Analisando o trecho “Acontecendo de o cientista provocar um dano em um local específico no cérebro”, verifica-se que ele estabelece com a oração seguinte uma relação de ', '3', '', '', 1),
(19, '(ENEM 2014)                              Censura Moralista \r\n\r\nHá tempos que a leitura está em pauta. E, diz-se, em crise. Comenta-se esta crise, por exemplo, apontando a precariedade das práticas de leitura, lamentando a falta de familiaridade dos jovens com livros, reclamando da falta de bibliotecas em tantos municípios, do preço dos livros em livrarias, num nunca acabar de problemas e de carências. Mas, de um tempo para cá, pesquisas acadêmicas vêm dizendo que talvez não seja exatamente assim, que brasileiros leem, sim, só que leem livros que as pesquisas tradicionais não levam em conta. E, também de um tempo para cá, políticas educacionais têm tomado a peito investir em livros e em leitura. \r\n\r\nLAJOLO, M. Disponível em: www.estadao.com.br. Acesso em: 2 dez. 2013 (fragmento). \r\n\r\nOs falantes, nos textos que produzem, sejam orais ou escritos, posicionam-se frente a assuntos que geram consenso ou despertam polêmica. \r\nNo texto, a autora ', '3', '', '', 1),
(20, '(ENEM 2014) eu acho um fato interessante… né… foi como meu pai e minha mãe vieram se conhecer… né… que… minha mãe morava no Piauí com toda família… né… meu… meu avô… materno no caso… era maquinista… ele sofreu um acidente… infelizmente morreu… minha mãe tinha cinco anos… né… e o irmão mais velho dela… meu padrinho… tinha dezessete e ele foi obrigado a trabalhar… foi trabalhar no banco… e… ele foi… o banco… no caso… estava… com um número de funcionários cheio e ele teve que ir para outro local e pediu transferência prum local mais perto de Parnaíba que era a cidade onde eles moravam e por engano o… o… escrivão entendeu Paraíba… né… e meu… e minha família veio parar em Mossoró que era exatamente o local mais perto onde tinha vaga pra funcionário do Banco do Brasil e:: ela foi parar na rua do meu pai… né… e começaram a se conhecer… namoraram onze anos… né… pararam algum tempo… brigaram… é lógico… porque todo relacionamento tem uma briga… né… e eu achei esse fato muito interessante porque foi uma coincidência incrível… né… como vieram a se conhecer… namoraram e hoje… e até hoje estão juntos… dezessete anos de casados… \r\n\r\nCUNHA, M. A. F. (Org.) . Corpus discurso & gramática: a língua falada e escrita na cidade do Natal. Natal: EdUFRN, 1998 \r\n\r\nNa transcrição de fala, há um breve relato de experiência pessoal, no qual se observa a frequente repetição de “né”. \r\nEssa repetição é um(a) ', '3', '', '', 1),
(21, '(ENEM /2018)  \r\nBRANCO, A. Disponível em: www.oesquema.com.br. Acesso em: 30 jun. 2015 (adaptado) \r\n\r\nA internet proporcionou o surgimento de novos paradigmas sociais e impulsionou a modificação de outros já estabelecidos nas esferas da comunicação e da informação. A principal consequência criticada na tirinha sobre esse processo é a ', '3', '', 'linguagens6.png', 1),
(22, '(Enem/2018) \r\n\r\nCerta vez minha mãe surrou-me com uma corda nodosa que me pintou as costas de manchas sangrentas. Moído, virando a cabeça com dificuldade, eu distinguia nas costelas grandes lanhos vermelhos. Deitaram-me, enrolaram-me em panos molhados com água de sal – e houve uma discussão na família. Minha avó, que nos visitava, condenou o procedimento da filha e esta afligiu-se. Irritada, ferira-me à toa, sem querer. Não guardei ódio a minha mãe: o culpado era o nó. \r\n\r\nRAMOS, G. Infância. Rio de Janeiro. Record, 1998. \r\n\r\nNum texto narrativo, a sequência dos fatos contribui para a progressão temática. No fragmento, esse processo é indicado pela ', '3', '', '', 1),
(23, '(Enem/2018) \r\n\r\nMais big do que bang \r\n\r\nA comunidade científica mundial recebeu, na semana passada, a confirmação oficial de uma descoberta sobre a qual se falava com enorme expectativa há alguns meses. Pesquisadores do Centro de Astrofísica Harvard-Smithsonian revelaram ter obtido a mais forte evidência até agora de que o universo em que vivemos começou mesmo pelo Big Bang, mas este não foi explosão, e sim uma súbita expansão de matéria e energia infinitas concentradas em um ponto microscópico que, sem muitas opções semânticas, os cientistas chamam de “singularidade”. Essa semente cósmica permanecia em estado latente e, sem que exista ainda uma explicação definitiva, começou a inchar rapidamente [...]. No intervalo de um piscar de olhos, por exemplo, seria possível, portanto, que ocorressem mais de 10 trilhões de Big Bangs. \r\n\r\nALLEGRETTI, F. Veja, 26 mar. 2014 (adaptado). \r\nNo título proposto para esse texto de divulgação científica, ao dissociar os elementos da expressão Big Bang, a autora revela a intenção de ', '3', '', '', 1),
(24, '(Enem/2022) \r\n\r\nA escrava \r\n\r\n— Admira-me —, disse uma senhora de sentimentos sinceramente abolicionistas —; faz-me até pasmar como se possa sentir, e expressar sentimentos escravocratas, no presente século, no século dezenove! A moral religiosa e a moral cívica aí se erguem, e falam bem alto esmagando a hidra que envenena a família no mais sagrado santuário seu, e desmoraliza, e avilta a nação inteira! Levantai os olhos ao Gólgota, ou percorrei-os em torno da sociedade, e dizei-me: \r\n\r\n— Para que se deu em sacrifício o Homem Deus, que ali exalou seu derradeiro alento? Ah! Então não é verdade que seu sangue era o resgate do homem! É então uma mentira abominável ter esse sangue comprado a liberdade!? E depois, olhai a sociedade... Não vedes o abutre que a corrói constantemente!… Não sentis a desmoralização que a enerva, o cancro que a destrói? \r\n\r\nPor qualquer modo que encaremos a escravidão, ela é, e será sempre um grande mal. Dela a decadência do comércio; porque o comércio e a lavoura caminham de mãos dadas, e o escravo não pode fazer florescer a lavoura; porque o seu trabalho é forçado. \r\n\r\nREIS, M. F. Úrsula e outras obras. Brasília: Câmara dos Deputados, 2018. \r\n\r\nInscrito na estética romântica da literatura brasileira, o conto descortina aspectos da realidade nacional no século XIX ao ', '3', '', '', 1),
(25, '(Enem/2017) \r\n\r\nEmotivo encuentro en la universidad pública \r\n\r\nEl entonces mandatario uruguayo recibió el cariño de sus compatriotas residentes en Nueva York e informó sobre la evolución del país, las políticas de gobierno, los avances y cuentas pendientes. Como en ocasiones similares, se multiplicaron las muestras de respeto y emoción. “Una nación es un formidable sentimiento de un ‘nosotros’”, dijo. \r\n\r\nMujica comenzó su discurso relatando lo recogido de otras experiencias de comunidades en el exilio. “Muchos de ustedes echaron raíces, tienen hijos y no pueden cometer la agresión de descuajarle la vida. Tienen que cargar con esa nostalgia de ser de allá, pero estar acá”, dijo. \r\n\r\n“Estamos metidos en la lucha por mejorar las circunstancias, con el sueño de que las generaciones que vengan, puedan venir con más soltura, con más apoyo”, dijo el Presidente. \r\n\r\nMujica se refirió a algunas críticas que reciben algunas políticas sociales. “Nos acusan de que damos sin contrapartida. Nos dicen ‘a la gente no hay que darle pescado, sino enseñarle a pescar’. Sí — razonó el Presidente —, pero cuando le afanaste la caña, le afanaste el bote, ¿qué le vas a pedir? Para atrás no arreglamos, arreglamos para adelante.” \r\n\r\nDisponível em: www.republica.com.uy. Acesso em: 26 set. 2013 (adaptado). \r\n\r\nNo discurso dirigido aos compatriotas radicados em Nova York, o então presidente Mujica expressa o desejo de que os cidadãos que vivem no Uruguai ', '3', '', '', 1),
(26, '(Enem/2016) \r\n\r\nDe tal palo, tal astilla \r\n\r\nCuando Michael Acuña ingresó en la Academy of Cuisine, en el estado de Maryland, ya hacía muchos soles que era un excelente cocinero. Es que sus padres, Manuel y Albita, fueron propietarios de El Mesón Tico, en Madrid, y, desde niño, Michael no salía de la cocina. \r\n\r\nYa graduado, trabajó en Washington, en Filomena’s Four Seasons, entre otros prestigiosos lugares. Cuando su familia regresó a su país, Costa Rica, y abrió Las Tapas de Manuel, al este de San José - la capital -, pronto se les reunió. \r\n\r\nEl éxito no se hizo esperar: inmediata ampliación, primero, y luego un segundo restaurante, esta vez al oeste de la ciudad, con tablado flamenco y un alegre bar \r\n\r\nMás de veinticinco tapas, clientes fieles que llegan una y otra vez, y una calidad constante, testimonian la razón de su éxito. \r\n\r\nROSS, M. American Airlines Nexos, n. 1, mar. 2003. \r\n\r\nO título do texto traz uma expressão idiomática. Essa expressão, vinculada às informações do texto, reforça que o sucesso alcançado por Michael Acuna deve-se ao fato de ele ter ', '3', '', '', 1),
(27, '(Enem/2018) \r\n\r\nEl carpintero \r\n\r\nOrlando Goicoechea reconoce las maderas por el olor, de qué árboles vienen, qué edad tienen, y oliéndolas sabe si fueron cortadas a tiempo o a destiempo y les adivina los posibles contratiempos. \r\nAl cabo de tantos años de trabajo, Orlando se ha dado el lujo de comprarse un video, y ve una película tras otra. \r\nNo sabía que eras loco por cine le dice el vecino. \r\nY Orlando le explica que no, que a él ni le va ni le viene, pero gracias al video puede detener las películas para estudiar los muebles. \r\n\r\nGALEANO, E. Disponivel em: http://elcajondesastre.blogcindarrio.com. Acesso em: 18 abr. 2012. \r\n\r\nNo conto de Galeano, a expressão ni le va ni le viene encerra uma opinião a respeito de cinema que ', '3', '', '', 1),
(28, '(Enem/2018) \r\n\r\nLava Mae: Creating Showers on Wheels for the Homeless \r\n\r\nSan Francisco, according to recent city numbers, has 4,300 people living on the streets. Among the many problems the homeless face is little or no access to showers. San Francisco only has about 16 to 20 shower stalls to accommodate them. \r\n\r\nBut Doniece Sandoval has made it her mission to change that. The 51-year-old former marketing executive started Lava Mae, a sort of showers on wheels, a new project that aims to turn decommissioned city buses into shower stations for the homeless. Each bus will have two shower stations and Sandoval expects that they\'ll be able to provide 2,000 showers a week. \r\n\r\nANDREANO, C. Dísponível em: abcnews.go.com. Acesso: 26 jun. 2015 (adaptado). \r\n\r\nA relação dos vocábulos shower, bus e homeless, no texto, refere-se a ', '3', '', '', 1),
(29, '(Enem 2017) \r\n\r\nOne of the things that made an incredible impression on me in the film was Frida’s comfort in and celebration of her own unique beauty. She didn’t try to fit into conventional ideas or images about womanhood or what makes someone or something beautiful. Instead, she fully inhabited her own unique gifts, not particularly caring what other people thought. She was magnetic and beautiful in her own right. She painted for years, not to be a commercial success or to be discovered, but to express her own inner pain, joy, family, love and culture. She absolutely and resolutely was who she was. The trueness of her own unique vision and her ability to stand firmly in her own truth was what made her successful in the end. \r\n\r\nHUTZLER, L. Disponível em: www.etbscreenwriting.com. Acesso em: 6 maio 2013 \r\n\r\nA autora desse comentário sobre o filme Frida mostra-se impressionada com o fato de a pintora  ', '3', '', '', 1),
(30, '(Enem 2017) \r\nNesse texto publicitário são utilizados recursos verbais e não verbais para transmitir a mensagem. Ao associar os termos anyplace e regret à imagem do texto, constata-se que o tema da propaganda é a importância da ', '3', '', 'linguagens7.png', 1),
(31, '(Enem/2018) \r\n\r\nCorredores ecológicos visam mitigar os efeitos da fragmentação dos ecossistemas promovendo a ligação entre diferentes áreas, com o objetivo de proporcionar o deslocamento de animais, a dispersão de sementes e o aumento da cobertura vegetal. São instituídos com base em informações como estudos sobre o deslocamento de espécies, sua área de vida (área necessária para o suprimento de suas necessidades vitais e reprodutivas) e a distribuição de suas populações. \r\n\r\nDisponível em: www.mma.gov.br. Acesso em: 30 nov. 2017 (adaptado) \r\n\r\nNessa estratégia, a recuperação da biodiversidade é efetiva porque: ', '1', '', '', 1),
(32, '(ENEM- 2022) \r\n\r\nAs células da epiderme da folha Tradescantia pallida purpurea, uma herbácea popularmente conhecida como trapoeraba-roxa, contém um vacúolo onde se encontra um pigmento que dá a coloração arroxeada a esse tecido. Em um experimento, um corte da epiderme de uma folha da trapoeraba-roxa foi imerso em ambiente hipotônico e logo em seguida, foi colocado em uma lâmina e observado em microscópio óptico. \r\n\r\nDurante a observação desse corte, foi possível identificar o(a) ', '1', '', '', 1),
(33, '(ENEM - 2021) O plantio por estaquia é um método de propagação de plantas no qual partes de um espécime são colocadas no solo para produzir novas gerações. Na floricultura, é comum utilizar o caule das roseiras para estaquia, pois a propagação da planta é positiva em razão da aplicação de auxinas na porção inferior do caule.  \r\n\r\nA utilização de auxinas no método de estaquia das roseiras contribui para  \r\n', '1', '', '', 1),
(34, '(ENEM - 2021)  \r\n\r\nNas angioispermas, além da fertilização da oosfera, existe uma segunda fertilização que resuta num tecido triploide.  Essa segunda fertilização foi importante evolutivamente, pois viabilizou a formação de um tecido de  ', '1', '', '', 1),
(35, '(ENEM 2017) \r\n\r\nA terapia celular tem sido amplamente divulgada como revolucionária, por emitir a regeneração de tecidos a partir de células novas. Entretanto, a técnica de se introduzirem novas células em um tecido, para o tratamento de enfermidades em indivíduos, já era aplicada rotineiramente em hospitais. \r\n\r\nA que técnica refere-se o texto? ', '1', '', '', 1),
(36, '(Enem-2018) Por meio de reações químicas que envolvem carboidratos, lipídeos e proteínas, nossas células obtêm energia e produzem gás carbônico e água. A oxidação da glicose no organismo humano libera energia, conforme ilustra a equação química, sendo que aproximadamente 40% dela é disponibilizada para atividade muscular. \r\n\r\nreto C com 6 subscrito reto H com 12 subscrito reto O com 6 parêntese esquerdo reto s parêntese direito espaço subscrito fim do subscrito espaço mais espaço 6 reto O com 2 parêntese esquerdo reto g parêntese direito subscrito fim do subscrito espaço seta para a direita espaço 6 CO com 2 parêntese esquerdo reto g parêntese direito subscrito fim do subscrito espaço mais espaço 6 reto H com 2 subscrito reto O com parêntese esquerdo reto l parêntese direito subscrito fim do subscrito espaço espaço espaço espaço incremento com reto c subscrito reto H espaço igual a espaço menos 2800 espaço kJ\r\nConsidere as massas molares em (em g mol-1):  \r\n\r\nreto H igual a 1 ponto e vírgula espaço reto C igual a 12 ponto e vírgula espaço reto O igual a 16.\r\nLIMA, L.M.; FRAGA, C.A.M; BARREIRO, E.J. Química na saúde. São Paulo: Sociedade Brasileira de Química, 2010 (adaptado). \r\n\r\nNa oxidação de 1,0 grama de glicose, a energia obtida para atividade muscular, em quilojoule, é mais próxima de ', '1', '', '', 1),
(37, '(Enem/2017) Art. 231. São reconhecidos aos índios sua organização social, costumes, línguas, crenças e tradições, e os direitos originários sobre as terras que tradicionalmente ocupam, competindo à União demarcá-las, proteger e fazer respeitar todos os seus bens. \r\n\r\nBRASIL. Constituição da República Federativa do Brasil de 1988. Disponível em: www.planalto.gov.br. Acesso em: 27 abr. 2017. \r\n\r\nA persistência das reivindicações relativas à aplicação desse preceito normativo tem em vista a vinculação histórica fundamental entre ', '2', '', '', 1),
(38, '(Enem/2017) Art. 231. São reconhecidos aos índios sua organização social, costumes, línguas, crenças e tradições, e os direitos originários sobre as terras que tradicionalmente ocupam, competindo à União demarcá-las, proteger e fazer respeitar todos os seus bens. \r\n\r\nBRASIL. Constituição da República Federativa do Brasil de 1988. Disponível em: www.planalto.gov.br. Acesso em: 27 abr. 2017. \r\n\r\nA persistência das reivindicações relativas à aplicação desse preceito normativo tem em vista a vinculação histórica fundamental entre ', '2', '', '', 1),
(39, '(Enem/2018) A tribo não possui um rei, mas um chefe que não é chefe de Estado. O que significa isso? Simplesmente que o chefe não dispõe de nenhuma autoridade, de nenhum poder de coerção, de nenhum meio de dar uma ordem. O chefe não é um comandante, as pessoas da tribo não têm nenhum dever de obediência. O espaço da chefia não é o lugar do poder. Essencialmente encarregado de eliminar conflitos que podem surgir entre indivíduos, famílias e linhagens, o chefe só dispõe, para restabelecer a ordem e a concórdia, do prestígio que lhe reconhece a sociedade. Mas evidentemente prestígio não significa poder, e os meios que o chefe detém para realizar sua tarefa de pacificador limitam-se ao uso exclusivo da palavra. \r\n\r\nCLASTRES, P. A sociedade contra o Estado. Rio de Janeiro. Francisco Alves, 1982 (adaptado). \r\n\r\nO modelo político das sociedades discutidas no texto contrasta com o do Estado liberal burguês porque se baseia em: ', '2', '', '', 1),
(40, '(Enem/2016) Quanto mais complicada se tornou a produção industrial, mais numerosos passaram a ser os elementos da indústria que exigiam garantia de fornecimento. Três deles eram de importância fundamental: o trabalho, a terra e o dinheiro. Numa sociedade comercial, esse fornecimento só poderia ser organizado de uma forma: tornando-os disponíveis à compra. Agora eles tinham que ser organizados para a venda no mercado. Isso estava de acordo com a exigência de um sistema de mercado. Sabemos que em um sistema como esse, os lucros só podem ser assegurados se se garante a autorregulação por meios de mercados competitivos interdependentes. \r\n\r\nPOLANYI, K. A grande transformação: As origens de nossa época. Rio de Janeiro: Campus, 2000 (Adaptado). \r\n\r\nA consequência do processo de transformação socioeconômica abordada no texto é a ', '2', '', '', 1),
(41, '(Enem/2016) Hoje, a indústria cultural assumiu a herança civilizatória da democracia de pioneiros e empresários, que tampouco desenvolvera uma fineza de sentido para os desvios espirituais. Todos são livres para dançar e para se divertir, do mesmo modo que, desde a neutralização histórica da religião, são livres para entrar em qualquer uma das inúmeras seitas. Mas a liberdade de escolha da ideologia, que reflete sempre a coerção econômica, revela-se em todos os setores como a liberdade de escolher o que é sempre a mesma coisa. \r\n\r\nADORNO, T HORKHEIMER, M. Dialética do esclarecimento: fragmentos filosóficos. Rio de Janeiro: Zahar, 1985. \r\n\r\nA liberdade de escolha na civilização ocidental, de acordo com a análise do texto, é um(a) ', '2', '', '', 1),
(42, '(Enem/2017) Uma conversação de tal natureza transforma o ouvinte; o contato de Sócrates paralisa e embaraça; leva a refletir sobre si mesmo, a imprimir à atenção uma direção incomum: os temperamentais, como Alcibíades sabem que encontrarão junto dele todo o bem de que são capazes, mas fogem porque receiam essa influência poderosa, que os leva a se censurarem. Sobretudo a esses jovens, muitos quase crianças, que ele tenta imprimir sua orientação. \r\n\r\nBREHIER, E. História da filosofia. São Paulo: Mestre Jou, 1977. \r\n\r\nO texto evidencia características do modo de vida socrático, que se baseava na ', '2', '', '', 1),
(43, '(Enem/2019) De fato, não é porque o homem pode usar a vontade livre para pecar que se deve supor que Deus a concedeu para isso. Há, portanto, uma razão pela qual Deus deu ao homem esta característica, pois sem ela não poderia viver e agir corretamente. Pode-se compreender, então, que ela foi concedida ao homem para esse fim, considerando-se que se um homem a usa para pecar, recairão sobre ele as punições divinas. Ora, isso seria injusto se a vontade livre tivesse sido dada ao homem não apenas para agir corretamente, mas também para pecar. Na verdade, por que deveria ser punido aquele que usasse sua vontade para o fim para o qual ela lhe foi dada? \r\nAGOSTINHO. O livre-arbítrio. In: MARCONDES, D. Textos básicos de ética. Rio de Janeiro: Jorge Zahar, 2008. \r\n\r\nNesse texto, o filósofo cristão Agostinho de Hipona sustenta que a punição divina tem como fundamento o(a) ', '2', '', '', 1),
(44, '(Enem/2013) Nasce daqui uma questão: se vale mais ser amado que temido ou temido que amado. Responde-se que ambas as coisas seriam de desejar; mas porque é difícil juntá-las, é muito mais seguro ser temido que amado, quando haja de faltar uma das duas. Porque dos homens que se pode dizer, duma maneira geral, que são ingratos, volúveis, simuladores, covardes e ávidos de lucro, e enquanto lhes fazes bem são inteiramente teus, oferecem-te o sangue, os bens, a vida e os filhos, quando, como acima disse, o perigo está longe; mas quando ele chega, revoltam-se. \r\n\r\nMAQUIAVEL, N. O Príncipe. Rio de Janeiro: Bertrand, 1991. \r\n\r\nA partir da análise histórica do comportamento humano em suas relações sociais e políticas, Maquiavel define o homem como um ser ', '2', '', '', 1),
(45, '(Enem/2019) Para Maquiavel, quando um homem decide dizer a verdade pondo em risco a própria integridade física, tal resolução diz respeito apenas a sua pessoa. Mas se esse mesmo homem é um chefe de Estado, os critérios pessoais não são mais adequados para decidir sobre ações cujas consequências se tornam tão amplas, já que o prejuízo não será apenas individual, mas coletivo. Nesse caso, conforme as circunstâncias e os fins a serem atingidos, pode-se decidir que o melhor para o bem comum seja mentir. \r\nARANHA, M. L. Maquiavel: a lógica da força. São Paulo: Moderna, 2006 (adaptado). \r\n\r\nO texto aponta uma inovação na teoria política na época moderna expressa na distinção entre ', '2', '', '', 1),
(46, '(Enem/2019) TEXTO I \r\nConsidero apropriado deter-me algum tempo na contemplação deste Deus todo perfeito, ponderar totalmente à vontade seus maravilhosos atributos, considerar, admirar e adorar a incomparável beleza dessa imensa luz. DESCARTES, R. Meditações. São Paulo: Abril Cultural, 1980. \r\n\r\nTEXTO II \r\nQual será a forma mais razoável de entender como é o mundo? Existirá alguma boa razão para acreditar que o mundo foi criado por uma divindade todo-poderosa? Não podemos dizer que a crença em Deus é “apenas” uma questão de fé. RACHELS, J. Problemas da filosofia. Lisboa: Gradiva, 2009. \r\n\r\nOs textos abordam um questionamento da construção da modernidade que defende um modelo ', '2', '', '', 1),
(47, '(Enem/2018) Em Beirute, no Líbano, quando perguntado sobre onde se encontram os refugiados sírios, a resposta do homem é imediata: “em todos os lugares e em lugar nenhum”. Andando ao acaso, não é raro ver, sob um prédio ou num canto de calçada, ao abrigo do vento, uma família refugiada em volta de uma refeição frugal posta sobre jornais como se fossem guardanapos. Também se vê de vez em quando uma tenda com a sigla ACNUR (Alto Comissariado das Nações Unidas para Refugiados), erguida em um dos raros terrenos vagos da capital. \r\nJABER, H. Quem realmente acolhe os refugiados? Le Monde Diplomatique Brasil, out.2015 (adaptado). \r\n\r\nO cenário descrito aponta para uma crise humanitária que é explicada pelo processo de ', '2', '', '', 1),
(48, '(Enem/2018) Os países industriais adotaram uma concepção diferente das relações familiares e do lugar da fecundidade na vida familiar e social. A preocupação de garantir uma transmissão integral das vantagens econômicas e sociais adquiridas tem como resultado uma ação voluntária de limitação do número de nascimentos. \r\n\r\nGEORGE, P. Panorama do mundo atual. São Paulo: Difusão Europeia do Livro, 1968 (adaptado). \r\n\r\nEm meados do século XX, o fenômeno social descrito contribuiu para o processo europeu de ', '2', '', '', 1),
(49, '(Enem/2017) O desgaste acelerado sempre existirá se o agricultor não tiver o devido cuidado de combater as causas, relacionadas a vários processos, tais como: empobrecimento químico e lixiviação provocados pelo esgotamento causado pelas colheitas e pela lavagem vertical de nutrientes da água que se infiltra no solo, bem como pela retirada de elementos nutritivos com as colheitas. Os nutrientes retirados, quando não repostos, são comumente substituídos por elementos tóxicos, como, por exemplo, o alumínio. \r\nLEPSCH, I. Formação e conservação dos solos. São Paulo: Oficinas de Texto, 2002 (adaptado). \r\n\r\nA dinâmica ambiental exemplificada no texto gera a seguinte consequência para o solo agricultável ', '2', '', '', 1),
(50, '(Enem/2015) Um carro esportivo e financiado pelo Japão, projetado na Itália e montado em Indiana, México e França, usando os mais avançados componentes eletrônicos, que foram inventados em Nova Jérsei e fabricados na Coreia. A campanha publicitária é desenvolvida na Inglaterra, filmada no Canadá, a edição e as cópias, feitas em Nova York para serem veiculadas no mundo todo. Teias globais disfarçam-se com o uniforme nacional que lhes for mais conveniente. \r\nREICH, R. O trabalho das nações: preparando-nos para o capitalismo no século XXI. São Paulo: Educator, 1994 (adaptado). \r\n\r\nA viabilidade do processo de produção ilustrado pelo texto pressupõe o uso de ', '2', '', '', 1),
(51, '(Enem/2019) Saudado por centenas de militantes de movimentos sociais de quarenta países, o papa Francisco encerrou no dia 09/07/2015 o 2º Encontro Mundial dos Movimentos Populares, em Santa Cruz de La Sierra, na Bolívia. Segundo ele, a “globalização da esperança, que nasce dos povos e cresce entre os pobres, deve substituir esta globalização da exclusão e da indiferença”. \r\nDisponível em: http://cartamaior.com.br. Acesso em: 15 jul. 2015 (adaptado). \r\n\r\nNo texto há uma crítica ao seguinte aspecto do mundo globalizado: ', '2', '', '', 1),
(52, '(Enem/2016) No aniversário do primeiro decênio da Marcha sobre Roma, em outubro de 1932, Mussolini irá inaugurar sua Via dell Impero; a nova Via Sacra do Fascismo, ornada com estátuas de César, Augusto, Trajano, servirá ao culto do antigo e à glória do Império Romano e de espaço comemorativo do ufanismo italiano. Às sombras do passado recriado ergue-se a nova Roma, que pode vangloriar-se e celebrar seus imperadores e homens fortes; seus grandes poetas e apólogos como Horácio e Virgílio. \r\n\r\nSILVA, G. História antiga e usos do passado um estudo de apropriações da Antiguidade sob o regime de Vichy. São Paulo: Annablume, 2007 (adaptado). \r\n\r\nA retomada da Antiguidade clássica pela perspectiva do patrimônio cultural foi realizada com o objetivo de ', '2', '', '', 1),
(53, 'Enem/2010) Para o Paraguai, portanto, essa foi uma guerra pela sobrevivência. De todo modo, uma guerra contra dois gigantes estava fadada a ser um teste debilitante e severo para uma economia de base tão estreita. Lopez precisava de uma vitória rápida e, se não conseguisse vencer rapidamente, provavelmente não venceria nunca. \r\n\r\nLYNCH, J. As Repúblicas do Prata: da Independência à Guerra do Paraguai. BETHELL, Leslie (Org). História da América Latina: da Independência até 1870, v. III. São Paulo: Edusp , 2004. \r\n\r\nA Guerra do Paraguai teve consequências políticas importantes para o Brasil, pois ', '2', '', '', 1),
(54, '(ENEM 2016)\r\nA imagem faz referência a uma intensa mobilização popular e pode ser traduzida como ', '2', '', 'hist3.png', 1),
(55, '(Enem/2014) As relações do Estado brasileiro com o movimento operário e sindical, bem como as políticas públicas voltadas para as questões sociais durante o primeiro governo da Era Vargas (1930-1945), são temas amplamente estudados pela academia brasileira em seus vários aspectos. São também os temas mais lembrados pela sociedade quando se pensa no legado varguista. \r\n\r\nD\'ARAUJO M. C. Estado, classe trabalhadora e políticas sociais. In: FERREIRA J.; DELGADO L. A. (Org.). O tempo do nacional-estatismo: Do início ao apogeu do Estado Novo. Rio de Janeiro: Civilização Brasileira, 2007. \r\n\r\nDurante o governo de Getúlio Vargas, foram desenvolvidas ações de cunho social, dentre as quais se destaca a  ', '2', '', '', 1),
(56, '(Enem/2011) Acompanhando a intenção da burguesia renascentista de ampliar seu domínio sobre a natureza e sobre o espaço geográfico, através da pesquisa científica e da invenção tecnológica, os cientistas também iriam se atirar nessa aventura, tentando conquistar a forma, o movimento, o espaço, a luz, a cor e mesmo a expressão e o sentimento. \r\n\r\n(SEVCENKO, N. O Renascimento, Campinas, Unicamp, 1984) \r\n\r\nO texto apresenta um espírito de época que afetou também a produção artística, marcada pela constante relação entre ', '2', '', '', 1);

--
-- Índices para tabelas despejadas
--

--
-- Índices para tabela `questoes`
--
ALTER TABLE `questoes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_Questoes_Questionario1_idx` (`Questionario_id`);

--
-- Restrições para despejos de tabelas
--

--
-- Limitadores para a tabela `questoes`
--
ALTER TABLE `questoes`
  ADD CONSTRAINT `fk_Questoes_Questionario1` FOREIGN KEY (`Questionario_id`) REFERENCES `questionario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
